### PR TITLE
data pages data collection

### PR DESCRIPTION
**Pull request by LorenzoBorje**
#422 

onClick handler at \<Link\/> to next page scoops up icon text and setState's the choice array

### CODE REVIEW

**Comment by dhowe** [comment]
this looks good
question: do we need the separate count variable, or can we just use choices.length ?

**Comment by LorenzoBorje** [comment]
choices.length would only available after the clicking on the next link
which depends on count to be visible

prior to this tried an alternate method where a handleClick function would count and index the choices in an array at the same time, but there was an issue with reading the DOM changes using a querySelector

**Comment by dhowe** [comment]
Ok, cool. One last question -- we want to allow users to select as many items as they want, but _at least_ 3 (or 2 in one case) before they can go on. Does this code handle more than 3 items?

**Comment by LorenzoBorje** [comment]
Yes it should, unlike this.count it's not tied to the number of items selected, it just queries the DOM for selected items according to the class that's applied when the items are selected.

**Pull request merged**
